language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "Bohan"
  - git config user.email "bohanzhang@foxmail.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - blog
env:
 global:
   - GH_REF: github.com/ZhangBohan/ZhangBohan.github.io.git
